version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    env_file:
      - .env.prod
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    links:
      - server
    depends_on:
      - server
    ports:
      - "3000:3000"
