version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    restart: always

  app:
    links:
      - postgres
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - ${PORT}:${PORT}


#  nginx:
#    image: nginx:1.17.1-alpine
#    container_name: nginx
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "8000:8000"
#    links:
#      - app
#    depends_on:
#      - app
