version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "5050:80"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "6000:6000"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
    depends_on:
      - server
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.17.1-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    links:
      - client
      - server
    depends_on:
      - client
      - server
