version: "3"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env.prod
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ../database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env.prod
    restart: always
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}

